namespace Server.Customs
{
    public enum TilePackType
    {
        GreyBrick,
        LightWood,
        DarkWood,
        Stone,
        StoneBlock,
        Log,
        LightWoodBanded,
        LightHeavyStone,
        OrnateWhiteMarble,
        TrimmedWhiteMarble,
        PlainWhiteMarble,
        TimberedPlainPlaster,
        PlainPlaster,
        OrnatePlaster,
        OrnateSandBlock,
        PlainSandBlock,
        HeavyStone,
        FormedSand,
        PlainBlueMarble,
        TrimmedBlueMarble,
        OrnateBlueMarble,
        WornPlaster,
        HeavilyWornPlaster,
        SmoothSandstone,
        HalfSmoothSandstone,
        Sandstone,
        TokunoWooden,
        DarkClothFrame,
        LightClothFrame,
        DarkClay,
        RoughClay,
        LightClay
    }
}
